version: 0.0
os: linux
files:
  - source: dist/my-angular-project/
    destination: /var/www/angular-app

permissions:
  - object: dist/my-angular-project/
    pattern: "**"
    owner: root
    group: root
    mode: '0755'
    type:
      - file
      - directory

hooks:
  ApplicationStart:
    - location: scripts/restart-nginx.sh
      timeout: 300

